import React, { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    code: "EN",
    name: "English",
    native: "Default",
    flag: "🇬🇧",
    greeting: 'NAMASTE, <span>SRINU</span>',
    subtitle: 'WHAT WOULD YOU LIKE TO GET DELIVERED TODAY?',
    promo1_badge: 'WELCOME OFFER',
    promo1_title: '20% OFF ON FIRST ORDER',
    promo1_desc: 'Use coupon code DPARCEL20 at checkout',
    promo1_btn: 'CLAIM OFFER NOW →',
    promo2_badge: 'REFERRAL REWARD',
    promo2_title: 'REFER A FRIEND & GET 20% OFF',
    promo2_desc: 'Share code REF20 & get 20% off when a friend orders',
    promo2_btn: 'REFER NOW →',
    how_it_works_title: 'How it works?',
    step1_title: 'Book service & address',
    step1_sub: 'Select from food, pharma, documents or custom parcel tasks.',
    step2_title: 'Instant rider pickup',
    step2_sub: 'Nearby verified delivery partner accepts your task immediately.',
    step3_title: 'Doorstep delivery',
    step3_sub: 'Live track your item with real-time GPS updates till delivery.',
    our_services: 'SERVICES',
    services_heading: 'SERVICES',
    claim_btn: 'CLAIM',
    food_title: 'FOOD PICKUP',
    food_sub: 'FAVORITE LOCAL HOTELS & RESTAURANTS',
    med_title: 'MEDICINE',
    med_sub: 'EXPRESS ESSENTIAL SUPPLIES',
    groc_title: 'GROCERIES',
    groc_sub: 'DAILY ESSENTIALS & FRESH PRODUCE',
    doc_title: 'SEND DOCUMENTS',
    doc_sub: 'SECURE COURIER & EXPRESS PARCEL',
    cust_title: 'CUSTOM TASKS',
    cust_sub: 'ANY PICKUP & DROP IN CITY',
    nav_home: 'Home',
    nav_orders: 'Orders',
    nav_support: 'Support',
    nav_settings: 'Settings',
    nav_logout: 'Logout',
    select_language_title: 'SELECT LANGUAGE',
    select_language_sub: 'Choose your preferred language for app translation',
    notif_center_title: 'NOTIFICATIONS CENTER',
    push_notif_title: 'Push Notifications',
    push_notif_sub: 'Receive delivery & promo updates',
    nearby_notif_title: 'Nearby Notifications',
    nearby_notif_sub: 'Alerts when rider or delivery is nearby',
    your_orders_title: 'YOUR <span>ORDERS</span>',
    orders_sub: 'Track live rider locations & view order history',
    all_orders: 'ALL ORDERS',
    active_orders: 'ACTIVE',
    completed_orders: 'COMPLETED',
    no_active_orders: 'No Active Orders Yet',
    start_ordering: 'START ORDERING →',
    rider_on_way: 'Rider On The Way',
    status_delivered: 'Delivered',
    mins_ago: 'mins ago',
    yesterday: 'Yesterday',
    food_pickup_type: 'Food Pickup',
    medicine_express_type: 'Medicine Express',
    send_documents_type: 'Send Documents',
    item_food_sample: '1x Hyderabadi Chicken Biryani, 2x Thumbs Up',
    item_med_sample: '1x First Aid Supplies, 1x Paracetamol 650mg',
    item_doc_sample: '1x Sealed Agreement Papers (Express Parcel)',
    how_can_we_help: 'HOW CAN WE <span>HELP?</span>',
    support_sub: 'Find answers about deliveries, payments, or live support.',
    call_support: 'Call Support',
    call_support_sub: 'Speak directly with our team',
    available_247: '● 24/7 Available',
    live_chat: 'Live Agent Chat',
    live_chat_sub: 'Average wait time: < 2 mins',
    start_chat_now: 'START CHAT NOW',
    faq_title: 'FREQUENTLY ASKED QUESTIONS',
    faq1_q: 'My payment failed but money was deducted',
    faq1_a: 'Any deducted amount for a failed transaction will automatically be refunded to your original payment method within 3 to 5 business days.',
    faq2_q: 'How do I track my live order?',
    faq2_a: 'Go to the Orders tab on the bottom navigation bar to view real-time location updates and rider contact details.',
    faq3_q: 'Can I change delivery address after booking?',
    faq3_a: 'Address changes are supported before a rider picks up your package. Use Live Chat for instant routing assistance.',
    recent_orders: 'RECENT ORDERS HISTORY',
    view_all: 'VIEW ALL',
    no_order_history: 'No previous order history.',
    settings_pref: 'Settings & Preferences',
    account_settings: 'ACCOUNT <span>SETTINGS</span>',
    settings_sub: 'Manage profile, preferences, and addresses',
    app_language: 'App Language',
    app_language_sub: 'Translate UI to Telugu, Kannada, Tamil & more',
    change_language_btn: 'CHANGE LANGUAGE',
    theme_mode: 'Theme Mode',
    theme_sub: 'Switch between Dark and Light mode',
    toggle_theme: 'TOGGLE THEME MODE',
    personal_details: 'Personal Details',
    personal_sub: 'Update public profile information',
    full_name: 'FULL NAME',
    phone_number: 'PHONE NUMBER',
    email_address: 'EMAIL ADDRESS',
    save_changes: 'SAVE CHANGES',
    saved_addresses: 'Saved Addresses',
    addresses_sub: 'Primary pickup & delivery locations',
    est_cost: 'Est. Cost',
    route_dist: 'Distance',
    confirm_order: 'CONFIRM ORDER'
  },
  te: {
    code: "TE",
    name: "Telugu",
    native: "తెలుగు",
    flag: "🇮🇳",
    greeting: 'నమస్కారం, <span>శ్రీను</span>',
    subtitle: 'ఈరోజు మీరు ఏమి డెలివరీ పొందాలనుకుంటున్నారు?',
    promo1_badge: 'స్వాగత ఆఫర్',
    promo1_title: 'మొదటి ఆర్డర్‌పై 20% డిస్కౌంట్ పొందండి',
    promo1_desc: 'చెక్‌అవుట్ వద్ద DPARCEL20 కూపన్ కోడ్ ఉపయోగించండి',
    promo1_btn: 'ఆఫర్ పొందండి →',
    promo2_badge: 'రెఫరల్ రివార్డ్',
    promo2_title: 'స్నేహితుడిని రెఫర్ చేయండి 20% ఆఫర్ పొందండి',
    promo2_desc: 'స్నేహితుడు ఆర్డర్ చేసినప్పుడు REF20 కోడ్ ద్వారా 20% ఆఫర్ పొందండి',
    promo2_btn: 'ఇప్పుడే రెఫర్ చేయండి →',
    how_it_works_title: 'ఇది ఎలా పనిచేస్తుంది?',
    step1_title: 'సేవ & చిరునామా ఎంచుకోండి',
    step2_title: 'తక్షణ రైడర్ పికప్',
    step3_title: 'డోర్‌స్టెప్ డెలివరీ',
    services_heading: 'సేవలు',
    food_title: 'ఫుడ్ పికప్',
    food_sub: 'మీకు ఇష్టమైన స్థానిక హోటళ్ళు & రెస్టారెంట్లు',
    med_title: 'మందులు (మెడిసిన్)',
    med_sub: 'అత్యవసర ఔషధాల వేగవంతమైన డెలివరీ',
    groc_title: 'కిరాణా సరుకులు',
    groc_sub: 'నిత్యవసర వస్తువులు & తాజా పండ్లు పాలు',
    doc_title: 'డాక్యుమెంట్లు పంపండి',
    doc_sub: 'సురక్షితమైన కొరియర్ & ఎక్స్‌ప్రెస్ పార్సెల్',
    cust_title: 'కస్టమ్ టాస్క్‌లు',
    cust_sub: 'నగరంలో ఏ పికప్ & డ్రాప్ అయినా',
    nav_home: 'హోమ్',
    nav_orders: 'ఆర్డర్లు',
    nav_support: 'సపోర్ట్',
    nav_settings: 'సెట్టింగ్‌లు',
    select_language_title: 'భాషను ఎంచుకోండి',
    select_language_sub: 'యాప్ అనువాదం కోసం మీ ప్రాధాన్య భాషను ఎంచుకోండి',
    notif_center_title: 'నోటిఫికేషన్స్ సెంటర్',
    push_notif_title: 'పుష్ నోటిఫికేషన్లు',
    push_notif_sub: 'డెలివరీ మరియు ఆఫర్ అప్‌డేట్‌లను పొందండి',
    nearby_notif_title: 'సమీప నోటిఫికేషన్లు',
    nearby_notif_sub: 'రైడర్ లేదా డెలివరీ సమీపంలో ఉన్నప్పుడు అప్‌డేట్‌లు',
    your_orders_title: 'మీ ఆర్డర్లు',
    orders_sub: 'లైవ్ రైడర్ లొకేషన్‌ను ట్రాక్ చేయండి & ఆర్డర్ హిస్టరీ చూడండి',
    all_orders: 'అన్ని ఆర్డర్లు',
    active_orders: 'ప్రస్తుత ఆర్డర్లు',
    completed_orders: 'పూర్తయినవి',
    no_active_orders: 'ఇంకా ఎటువంటి యాక్టివ్ ఆర్డర్లు లేవు',
    start_ordering: 'ఆర్డర్ చేయడం ప్రారంభించండి →',
    rider_on_way: 'రైడర్ వస్తున్నారు',
    status_delivered: 'డెలివరీ పూర్తయింది',
    mins_ago: 'నిమిషాల క్రితం',
    yesterday: 'నిన్న',
    food_pickup_type: 'ఫుడ్ పికప్',
    medicine_express_type: 'మెడిసిన్ ఎక్స్‌ప్రెస్',
    send_documents_type: 'డాక్యుమెంట్లు పంపండి',
    item_food_sample: '1x హైదరాబాదీ చికెన్ బిర్యానీ, 2x థంబ్స్ అప్',
    item_med_sample: '1x ఫస్ట్ ఎయిడ్ సప్లైస్, 1x పారాసిటమాల్ 650mg',
    item_doc_sample: '1x సీల్ చేసిన ఒప్పంద పత్రాలు (ఎక్స్‌ప్రెస్ పార్సెల్)',
    how_can_we_help: 'మేము మీకు ఎలా సహాయపడగలము?',
    support_sub: 'డెలివరీలు, చెల్లింపులు లేదా ప్రత్యక్ష మద్దతు కోసం సమాధానాలను పొందండి.',
    call_support: 'కాల్ సపోర్ట్',
    call_support_sub: 'వెంటనే ఏజెంట్‌తో మాట్లాడండి.',
    available_247: '● 24/7 అందుబాటులో ఉంది',
    live_chat: 'లైవ్ చాట్',
    live_chat_sub: 'సగటు వేచి ఉండే సమయం: < 2 నిమిషాలు',
    start_chat_now: 'ఇప్పుడే చాట్ ప్రారంభించండి',
    faq_title: 'తరచుగా అడిగే ప్రశ్నలు',
    faq1_q: 'నా పేమెంట్ ఫెయిల్ అయింది కానీ డబ్బు కట్ అయింది',
    faq1_a: 'విఫలమైన లావాదేవీల కోసం కట్ అయిన మొత్తం 3 నుండి 5 పని దినాలలో మీ పేమెంట్ అకౌంట్‌కు రీఫండ్ చేయబడుతుంది.',
    faq2_q: 'నా లైవ్ ఆర్డర్‌ను ఎలా ట్రాక్ చేయాలి?',
    faq2_a: 'రియల్ టైమ్ లొకేషన్ మరియు రైడర్ కాంటాక్ట్ వివరాల కోసం ఆర్డర్‌ల ట్యాబ్‌కు వెళ్లండి.',
    faq3_q: 'బుకింగ్ తర్వాత డెలివరీ అడ్రస్ మార్చవచ్చా?',
    faq3_a: 'రైడర్ ప్యాకేజీని పికప్ చేయడానికి ముందు చిరునామా మార్పులకు మద్దతు ఉంది.',
    recent_orders: 'ఇటీవలి ఆర్డర్ల చరిత్ర',
    view_all: 'అన్నీ చూడండి',
    no_order_history: 'గత ఆర్డర్ చరిత్ర లేదు.',
    settings_pref: 'సెట్టింగ్‌లు & ప్రాధాన్యతలు',
    account_settings: 'ఖాతా సెట్టింగ్‌లు',
    settings_sub: 'ప్రొఫైల్, ప్రాధాన్యతలు మరియు చిరునామాలను నిర్వహించండి',
    app_language: 'యాప్ భాష',
    app_language_sub: 'తెలుగు, కన్నడ, తమిళం మొదలైన భాషలలోకి మార్చండి',
    change_language_btn: 'భాషను మార్చండి',
    theme_mode: 'థీమ్ మోడ్',
    theme_sub: 'డార్క్ మరియు లైట్ మోడ్ మధ్య మారండి',
    toggle_theme: 'థీమ్ మోడ్ మార్చండి',
    personal_details: 'వ్యక్తిగత వివరాలు',
    personal_sub: 'మీ ప్రొఫైల్ వివరాలను నవీకరించండి',
    full_name: 'పూర్తి పేరు',
    phone_number: 'ఫోన్ నంబరు',
    email_address: 'ఈమెయిల్ చిరునామా',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    saved_addresses: 'సేవ్ చేసిన చిరునామాలు',
    addresses_sub: 'ముఖ్యమైన పికప్ & డెలివరీ స్థానాలు',
    est_cost: 'అంచనా వ్యయం',
    route_dist: 'రూట్ దూరం',
    confirm_order: 'ఆర్డర్ నిశ్చయించండి'
  },
  kn: {
    code: "KA",
    name: "Kannada",
    native: "ಕನ್ನಡ",
    flag: "🇮🇳",
    greeting: 'ನಮಸ್ಕಾರ, <span>ಶ್ರೀನು</span>',
    subtitle: 'ಇಂದು ನೀವು ಏನನ್ನು ಡೆಲಿವರಿ ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ?',
    promo1_badge: 'ಸ್ವಾಗತ ಆಫರ್',
    promo1_title: 'ಮೊದಲ ಆರ್ಡರ್‌ನಲ್ಲಿ 20% ರಿಯಾಯಿತಿ ಪಡೆಯಿರಿ',
    promo1_desc: 'ಚೆಕ್‌ಔಟ್‌ನಲ್ಲಿ DPARCEL20 ಕೂಪನ್ ಕೋಡ್ ಬಳಸಿ',
    promo1_btn: 'ಆಫರ್ ಪಡೆಯಿರಿ →',
    promo2_badge: 'ರೆಫರಲ್ ಬಹುಮಾನ',
    promo2_title: 'ಸ್ನೇಹಿತರಿಗೆ ರೆಫರ್ ಮಾಡಿ 20% ರಿಯಾಯಿತಿ ಪಡೆಯಿರಿ',
    promo2_desc: 'ಸ್ನೇಹಿತರು ಆರ್ಡರ್ ಮಾಡಿದಾಗ REF20 ಕೋಡ್ ಬಳಸಿ 20% ರಿಯಾಯಿತಿ ಪಡೆಯಿರಿ',
    promo2_btn: 'ಈಗಲೇ ರೆಫರ್ ಮಾಡಿ →',
    how_it_works_title: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ?',
    step1_title: 'ಸೇವೆ & ವಿಳಾಸ ಆಯ್ಕೆಮಾಡಿ',
    step2_title: 'ತಕ್ಷಣದ ರೈಡರ್ ಪಿಕಪ್',
    step3_title: 'ಡೋರ್‌ಸ್ಟೆಪ್ ಡೆಲಿವರಿ',
    services_heading: 'ಸೇವೆಗಳು',
    food_title: 'ಫುಡ್ ಪಿಕಪ್',
    food_sub: 'ನಿಮ್ಮ ನೆಚ್ಚಿನ ಸ್ಥಳೀಯ ಹೋಟೆಲ್‌ಗಳು & ರೆಸ್ಟೋರೆಂಟ್‌ಗಳು',
    med_title: 'ಔಷಧಿಗಳು (ಮೆಡಿಸಿನ್)',
    med_sub: 'ಅಗತ್ಯ ವೈದ್ಯಕೀಯ ಸರಬರಾಜು',
    groc_title: 'ಕಿರಾಣಿ ಸಾಮಗ್ರಿಗಳು',
    groc_sub: 'ದೈನಂದಿನ ಅಗತ್ಯ ವಸ್ತುಗಳು & ತಾಜಾ ಪದಾರ್ಥಗಳು',
    doc_title: 'ದಾಖಲೆಗಳನ್ನು ಕಳುಹಿಸಿ',
    doc_sub: 'ಸುರಕ್ಷಿತ ಕೊರಿಯರ್ & ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಪಾರ್ಸಲ್',
    cust_title: 'ಕಸ್ಟಮ್ ಟಾಸ್ಕ್‌ಗಳು',
    cust_sub: 'ನಗರದಲ್ಲಿ ಯಾವುದೇ ಪಿಕಪ್ ಮತ್ತು ಡ್ರಾಪ್',
    nav_home: 'ಹೋಮ್',
    nav_orders: 'ಆರ್ಡರ್‌ಗಳು',
    nav_support: 'ಬೆಂಬಲ',
    nav_settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    select_language_title: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    select_language_sub: 'ಆ್ಯಪ್ ಅನುವಾದಕ್ಕಾಗಿ ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    notif_center_title: 'ನೋಟಿಫಿಕೇಶನ್ ಸೆಂಟರ್',
    push_notif_title: 'ಪುಷ್ ನೋಟಿಫಿಕೇಶನ್‌ಗಳು',
    push_notif_sub: 'ಡೆಲಿವರಿ ಮತ್ತು ಆಫರ್ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
    nearby_notif_title: 'ಸಮೀಪದ ನೋಟಿಫಿಕೇಶನ್‌ಗಳು',
    nearby_notif_sub: 'ರೈಡರ್ ಅಥವಾ ಡೆಲಿವರಿ ಹತ್ತಿರದಲ್ಲಿದ್ದಾಗ ಎಚ್ಚರಿಕೆಗಳು',
    your_orders_title: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳು',
    orders_sub: 'ಲೈವ್ ರೈಡರ್ ಸ್ಥಳವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ & ಇತಿಹಾಸವನ್ನು ವೀಕ್ಷಿಸಿ',
    all_orders: 'ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು',
    active_orders: 'ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳು',
    completed_orders: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    no_active_orders: 'ಇನ್ನೂ ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ',
    start_ordering: 'ಆರ್ಡರ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ →',
    rider_on_way: 'ರೈಡರ್ ದಾರಿಯಲ್ಲಿದ್ದಾರೆ',
    status_delivered: 'ಡೆಲಿವರಿ ಪೂರ್ಣಗೊಂಡಿದೆ',
    mins_ago: 'ನಿಮಿಷಗಳ ಹಿಂದೆ',
    yesterday: 'ನಿನ್ನೆ',
    food_pickup_type: 'ಫುಡ್ ಪಿಕಪ್',
    medicine_express_type: 'ಮೆಡಿಸಿನ್ ಎಕ್ಸ್‌ಪ್ರೆಸ್',
    send_documents_type: 'ದಾಖಲೆಗಳನ್ನು ಕಳುಹಿಸಿ',
    item_food_sample: '1x ಹೈದರಾಬಾದಿ ಚಿಕನ್ ಬಿರಿಯಾನಿ, 2x ಥಂಬ್ಸ್ ಅಪ್',
    item_med_sample: '1x ಪ್ರಥಮ ಚಿಕಿತ್ಸಾ ಸಾಮಗ್ರಿಗಳು, 1x ಪ್ಯಾರಾಸಿಟಮಾಲ್ 650mg',
    item_doc_sample: '1x ಮುಚ್ಚಿದ ಒಪ್ಪಂದದ ಪತ್ರಗಳು (ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಪಾರ್ಸಲ್)',
    how_can_we_help: 'ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    support_sub: 'ಡೆಲಿವರಿ, ಪಾವತಿ ಅಥವಾ ನೇರ ಸಹಾಯಕ್ಕಾಗಿ ಉತ್ತರಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.',
    call_support: 'ಕಾಲ್ ಸಪೋರ್ಟ್',
    call_support_sub: 'ತಕ್ಷಣವೇ ಏಜೆಂಟ್ ಜೊತೆ ಮಾತನಾಡಿ.',
    available_247: '● 24/7 ಲಭ್ಯವಿದೆ',
    live_chat: 'ಲೈವ್ ಚಾಟ್',
    live_chat_sub: 'ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ: < 2 ನಿಮಿಷಗಳು',
    start_chat_now: 'ಈಗ ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    faq_title: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    faq1_q: 'ನನ್ನ ಪಾವತಿ ವಿಫಲವಾಗಿದೆ ಆದರೆ ಹಣ ಕಡಿತಗೊಂಡಿದೆ',
    faq1_a: 'ವಿಫಲವಾದ ವಹಿವಾಟಿಗೆ ಕಡಿತಗೊಂಡ ಮೊತ್ತವು 3 ರಿಂದ 5 ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ಮರುಪಾವತಿಯಾಗುತ್ತದೆ.',
    faq2_q: 'ನನ್ನ ಲೈವ್ ಆರ್ಡರ್ ಅನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು ಹೇಗೆ?',
    faq2_a: 'ಸ್ಥಳ ಮತ್ತು ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಲು ಕೆಳಗಿನ ಆರ್ಡರ್‌ಗಳ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ.',
    faq3_q: 'ಬುಕಿಂಗ್ ನಂತರ ಡೆಲಿವರಿ ವಿಳಾಸ ಬದಲಾಯಿಸಬಹುದೇ?',
    faq3_a: 'ರೈಡರ್ ಪಿಕಪ್ ಮಾಡುವ ಮೊದಲು ವಿಳಾಸ ಬದಲಾವಣೆಗೆ ಬೆಂಬಲವಿದೆ.',
    recent_orders: 'ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳ ಇತಿಹಾಸ',
    view_all: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    no_order_history: 'ಯಾವುದೇ ಹಿಂದಿನ ಆರ್ಡರ್ ಇತಿಹಾಸವಿಲ್ಲ.',
    settings_pref: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು',
    account_settings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    settings_sub: 'ಪ್ರೊಫೈಲ್, ಆದ್ಯತೆಗಳು ಮತ್ತು ವಿಳಾಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    app_language: 'ಆ್ಯಪ್ ಭಾಷೆ',
    app_language_sub: 'ತೆಲುಗು, ಕನ್ನಡ, ತಮಿಳು ಭಾಷೆಗಳಿಗೆ ಬದಲಾಯಿಸಿ',
    change_language_btn: 'ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ',
    theme_mode: 'ಥೀಮ್ ಮೋಡ್',
    theme_sub: 'ಡಾರ್ಕ್ ಮತ್ತು ಲೈಟ್ ಮೋಡ್ ನಡುವೆ ಬದಲಾಯಿಸಿ',
    toggle_theme: 'ಥೀಮ್ ಮೋಡ್ ಬದಲಾಯಿಸಿ',
    personal_details: 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
    personal_sub: 'ಸಾರ್ವಜನಿಕ ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    phone_number: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    email_address: 'ಇಮೇಲ್ ವಿಳಾಸ',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    saved_addresses: 'ಉಳಿಸಿದ ವಿಳಾಸಗಳು',
    addresses_sub: 'ಪ್ರಾಥಮಿಕ ಪಿಕಪ್ ಮತ್ತು ಡೆಲಿವರಿ ಸ್ಥಳಗಳು',
    est_cost: 'ಅಂದಾಜು ವೆಚ್ಚ',
    route_dist: 'ರೂಟ್ ದೂರ',
    confirm_order: 'ಆರ್ಡರ್ ದೃಢೀಕರಿಸಿ'
  },
  ta: {
    code: "TA",
    name: "Tamil",
    native: "தமிழ்",
    flag: "🇮🇳",
    greeting: 'வணக்கம், <span>ஶ்ரீனு</span>',
    subtitle: 'இன்று உங்களுக்கு என்ன விநியோகம் செய்ய வேண்டும்?',
    promo1_badge: 'வரவேற்பு சலுகை',
    promo1_title: 'முதல் ஆர்டருக்கு 20% தள்ளுபடி பெறுங்கள்',
    promo1_desc: 'செக்அவுட்டில் DPARCEL20 கூப்பன் குறியீட்டைப் பயன்படுத்தவும்',
    promo1_btn: 'சலுகையைப் பெறுங்கள் →',
    promo2_badge: 'பரிந்துரை வெகுமதி',
    promo2_title: 'நண்பருக்குப் பரிந்துரைத்து 20% தள்ளுபடி பெறுங்கள்',
    promo2_desc: 'நண்பர் ஆர்டர் செய்யும் போது REF20 குறியீடு மூலம் 20% தள்ளுபடி பெறுங்கள்',
    promo2_btn: 'இப்போதே பரிந்துரைக்கவும் →',
    how_it_works_title: 'இது எவ்வாறு செயல்படுகிறது?',
    step1_title: 'சேவை & முகவரி தேர்வு',
    step2_title: 'உடனடி ரைடர் பிக்கப்',
    step3_title: 'வாசல் விநியோகம்',
    services_heading: 'சேவைகள்',
    food_title: 'உணவு பிக்கப்',
    food_sub: 'பிடித்த உணவகங்கள் மற்றும் ஹோட்டல்கள்',
    med_title: 'மருந்துகள் (மெடிசின்)',
    med_sub: 'அத்தியாவசிய மருத்துவ விநியோகம்',
    groc_title: 'மளிகைப் பொருட்கள்',
    groc_sub: 'தினசரி அத்தியாவசியப் பொருட்கள் & காய்கறிகள்',
    doc_title: 'ஆவணங்களை அனுப்புங்கள்',
    doc_sub: 'பாதுகாப்பான கூரியர் & எக்ஸ்பிரஸ் பார்சல்',
    cust_title: 'சிறப்பு பணிகள்',
    cust_sub: 'நகரத்திற்குள் ஏதேனும் பிக்கப் & டிராப்',
    nav_home: 'முகப்பு',
    nav_orders: 'ஆர்டர்கள்',
    nav_support: 'உதவி',
    nav_settings: 'அமைப்புகள்',
    select_language_title: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    select_language_sub: 'செயலி மொழிபெயர்ப்பிற்கு உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்',
    notif_center_title: 'அறிவிப்பு மையம்',
    push_notif_title: 'புஷ் அறிவிப்புகள்',
    push_notif_sub: 'டெலிவரி மற்றும் சலுகை அறிவிப்புகளைப் பெறுங்கள்',
    nearby_notif_title: 'அருகிலுள்ள அறிவிப்புகள்',
    nearby_notif_sub: 'ரைடர் அல்லது டெலிவரி அருகில் இருக்கும் போது அறிவிப்பு',
    your_orders_title: 'உங்கள் ஆர்டர்கள்',
    orders_sub: 'நேரலை ரைடர் இருப்பிடத்தைக் கண்காணித்து வரலாற்றுப் பதிவைக் காண்க',
    all_orders: 'அனைத்து ஆர்டர்கள்',
    active_orders: 'நடப்பு ஆர்டர்கள்',
    completed_orders: 'நிறைவடைந்தவை',
    no_active_orders: 'இன்னும் எந்த ஆர்டரும் இல்லை',
    start_ordering: 'ஆர்டர் செய்யத் தொடங்குங்கள் →',
    rider_on_way: 'ரைடர் வந்துகொண்டிருக்கிறார்',
    status_delivered: 'டெலிவரி முடிந்தது',
    mins_ago: 'நிமிடங்களுக்கு முன்',
    yesterday: 'நேற்று',
    food_pickup_type: 'உணவு பிக்கப்',
    medicine_express_type: 'மெடிசின் எக்ஸ்பிரஸ்',
    send_documents_type: 'ஆவணங்களை அனுப்புங்கள்',
    item_food_sample: '1x ஹைதராபாத் சிக்கன் பிரியாணி, 2x தம்ஸ் அப்',
    item_med_sample: '1x முதலுதவிப் பொருட்கள், 1x பாராசிட்டமால் 650mg',
    item_doc_sample: '1x சீல் செய்யப்பட்ட ஒப்பந்தப் பத்திரங்கள் (எக்ஸ்பிரஸ் பார்சல்)',
    how_can_we_help: 'நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?',
    support_sub: 'டெலிவரி, கட்டணங்கள் அல்லது நேரலை உதவிக்கான பதில்களைக் கண்டறியவும்.',
    call_support: 'அழைப்பு உதவி',
    call_support_sub: 'உடனடியாக உதவியாளருடன் பேசுங்கள்.',
    available_247: '● 24/7 கிடைக்கிறது',
    live_chat: 'நேரலை அரட்டை',
    live_chat_sub: 'சராசரி காத்திருப்பு நேரம்: < 2 நிமிடங்கள்',
    start_chat_now: 'இப்போது அரட்டையைத் தொடங்குங்கள்',
    faq_title: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faq1_q: 'பணம் பிடித்தம் செய்யப்பட்டது ஆனால் ஆர்டர் தோல்வியடைந்தது',
    faq1_a: 'தோல்வியடைந்த பரிவர்த்தனைக்கான தொகை 3 முதல் 5 வேலை நாட்களுக்குள் திருப்பித் தரப்படும்.',
    faq2_q: 'எனது நேரலை ஆர்டரை எவ்வாறு கண்காணிப்பது?',
    faq2_a: 'விவரங்களைக் காண கீழே உள்ள ஆர்டர்கள் பகுதிக்குச் செல்லவும்.',
    faq3_q: 'பதிவு செய்த பிறகு முகவரியை மாற்ற முடியுமா?',
    faq3_a: 'பார்சலை எடுப்பதற்கு முன்பு முகவரி மாற்றங்கள் ஆதரிக்கப்படுகின்றன.',
    recent_orders: 'சமீபத்திய ஆர்டர் வரலாறு',
    view_all: 'அனைத்தையும் காண்க',
    no_order_history: 'முந்தைய ஆர்டர் வரலாறு இல்லை.',
    settings_pref: 'அமைப்புகள் & விருப்பத்தேர்வுகள்',
    account_settings: 'கணக்கு அமைப்புகள்',
    settings_sub: 'சுயவிவரம் மற்றும் முகவரிகளை நிர்வகிக்கவும்',
    app_language: 'செயலி மொழி',
    app_language_sub: 'தெலுங்கு, கன்னடம், தமிழ் மொழிகளுக்கு மாற்றவும்',
    change_language_btn: 'மொழியை மாற்றவும்',
    theme_mode: 'தீம் முறை',
    theme_sub: 'டார்க் மற்றும் லைட் முறைக்கு மாறவும்',
    toggle_theme: 'தீம் முறையை மாற்றவும்',
    personal_details: 'தனிப்பட்ட விவரங்கள்',
    personal_sub: 'சுயவிவரத் தகவலைப் புதுப்பிக்கவும்',
    full_name: 'முழு பெயர்',
    phone_number: 'தொலைபேசி எண்',
    email_address: 'மின்னஞ்சல் முகவரி',
    save_changes: 'மாற்றங்களைச் சேமிக்கவும்',
    saved_addresses: 'சேமித்த முகவரிகள்',
    addresses_sub: 'முதன்மை பிக்கப் & டெலிவரி முகவரிகள்',
    est_cost: 'மதிப்பிடப்பட்ட கட்டணம்',
    route_dist: 'தூரம்',
    confirm_order: 'ஆர்டரை உறுதிப்படுத்துக'
  },
  hi: {
    code: "HI",
    name: "Hindi",
    native: "हिंदी",
    flag: "🇮🇳",
    greeting: 'नमस्ते, <span>श्रीनु</span>',
    subtitle: 'आज आप क्या डिलीवर करवाना चाहते हैं?',
    promo1_badge: 'वेलकम ऑफर',
    promo1_title: 'पहले ऑर्डर पर 20% की छूट पाएं',
    promo1_desc: 'चेकआउट पर DPARCEL20 कूपन कोड का उपयोग करें',
    promo1_btn: 'ऑफर क्लेम करें →',
    promo2_badge: 'रेफरल इनाम',
    promo2_title: 'दोस्तों को रेफर करें और 20% छूट पाएं',
    promo2_desc: 'कोड REF20 शेयर करें और दोस्त के ऑर्डर पर 20% छूट पाएं',
    promo2_btn: 'अभी रेफर करें →',
    how_it_works_title: 'यह कैसे काम करता है?',
    step1_title: 'सेवा और पता चुनें',
    step2_title: 'तुरंत राइडर पिकअप',
    step3_title: 'डोरस्टेप डिलीवरी',
    services_heading: 'हमारी सेवाएं',
    food_title: 'फूड पिकअप',
    food_sub: 'पसंदीदा स्थानीय होटल और रेस्टोरेंट',
    med_title: 'दवाइयां (मेडिसिन)',
    med_sub: 'जरूरी दवाइयों की एक्सप्रेस डिलीवरी',
    groc_title: 'किराना सामान',
    groc_sub: 'दैनिक जरूरत की चीजें और ताजा सामान',
    doc_title: 'डॉक्यूमेंट्स भेजें',
    doc_sub: 'सुरक्षित कूरियर और पार्सल सेवा',
    cust_title: 'कस्टम टास्क (अन्य काम)',
    cust_sub: 'शहर में कोई भी पिकअप और ड्रॉप',
    nav_home: 'होम',
    nav_orders: 'ऑर्डर',
    nav_support: 'सपोर्ट',
    nav_settings: 'सेटिंग्स',
    select_language_title: 'भाषा चुनें',
    select_language_sub: 'ऐप अनुवाद के लिए अपनी पसंदीदा भाषा चुनें',
    notif_center_title: 'नोटिफिकेशन सेंटर',
    push_notif_title: 'पुश नोटिफिकेशन',
    push_notif_sub: 'डिलीवरी और ऑफर अपडेट प्राप्त करें',
    nearby_notif_title: 'पास की नोटिफिकेशन',
    nearby_notif_sub: 'जब राइडर या डिलीवरी पास हो तो अलर्ट प्राप्त करें',
    your_orders_title: 'आपके ऑर्डर',
    orders_sub: 'लाइव राइडर लोकेशन ट्रैक करें और ऑर्डर इतिहास देखें',
    all_orders: 'सभी ऑर्डर',
    active_orders: 'एक्टिव ऑर्डर',
    completed_orders: 'पूरे हुए',
    no_active_orders: 'अभी कोई एक्टिव ऑर्डर नहीं है',
    start_ordering: 'ऑर्डर करना शुरू करें →',
    rider_on_way: 'राइडर रास्ते में है',
    status_delivered: 'डिलीवर हो गया',
    mins_ago: 'मिनट पहले',
    yesterday: 'कल',
    food_pickup_type: 'फूड पिकअप',
    medicine_express_type: 'मेडिसिन एक्सप्रेस',
    send_documents_type: 'डॉक्यूमेंट्स भेजें',
    item_food_sample: '1x हैदराबादी चिकन बिरयानी, 2x थम्स अप',
    item_med_sample: '1x फर्स्ट एड सामान, 1x पैरासिटामोल 650mg',
    item_doc_sample: '1x सील किए गए एग्रीमेंट पेपर (एक्सप्रेस पार्सल)',
    how_can_we_help: 'हम आपकी क्या सहायता कर सकते हैं?',
    support_sub: 'डिलीवरी, भुगतान या लाइव सपोर्ट के लिए उत्तर खोजें।',
    call_support: 'कॉल सपोर्ट',
    call_support_sub: 'एजेंट से तुरंत बात करें।',
    available_247: '● 24/7 उपलब्ध',
    live_chat: 'लाइव चैट',
    live_chat_sub: 'औसत प्रतीक्षा समय: < 2 मिनट',
    start_chat_now: 'अभी चैट शुरू करें',
    faq_title: 'अक्सर पूछे जाने वाले प्रश्न',
    faq1_q: 'मेरा भुगतान विफल हो गया लेकिन पैसे कट गए',
    faq1_a: 'विफल लेनदेन के लिए काटी गई राशि 3 से 5 कार्य दिवसों में स्वचालित रूप से वापस आ जाएगी।',
    faq2_q: 'मैं अपना लाइव ऑर्डर कैसे ट्रैक करूं?',
    faq2_a: 'लोकेशन और संपर्क विवरण देखने के लिए नीचे दिए गए ऑर्डर टैब पर जाएं।',
    faq3_q: 'क्या मैं बुकिंग के बाद डिलीवरी पता बदल सकता हूं?',
    faq3_a: 'पैकेज पिकअप करने से पहले पता बदला जा सकता है।',
    recent_orders: 'हाल के ऑर्डर का इतिहास',
    view_all: 'सभी देखें',
    no_order_history: 'कोई पिछला ऑर्डर इतिहास नहीं है।',
    settings_pref: 'सेटिंग्स और प्राथमिकताएं',
    account_settings: 'अकाउंट सेटिंग्स',
    settings_sub: 'प्रोफ़ाइल, प्राथमिकताओं और पतों को प्रबंधित करें',
    app_language: 'ऐप भाषा',
    app_language_sub: 'तेलुगु, कन्नड़, तमिल आदि भाषा में बदलें',
    change_language_btn: 'भाषा बदलें',
    theme_mode: 'थीम मोड',
    theme_sub: 'डार्क और लाइट मोड के बीच स्विच करें',
    toggle_theme: 'थीम मोड बदलें',
    personal_details: 'व्यक्तिगत विवरण',
    personal_sub: 'अपनी प्रोफ़ाइल जानकारी अपडेट करें',
    full_name: 'पूरा नाम',
    phone_number: 'फोन नंबर',
    email_address: 'ईमेल पता',
    save_changes: 'बदलाव सहेजें',
    saved_addresses: 'सहेजे गए पते',
    addresses_sub: 'मुख्य पिकअप और डिलीवरी स्थान',
    est_cost: 'अनुमानित लागत',
    route_dist: 'दूरी',
    confirm_order: 'ऑर्डर की पुष्टि करें'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('selectedLang') || 'en';
  });

  const selectLanguage = (langCode) => {
    setCurrentLang(langCode);
    localStorage.setItem('selectedLang', langCode);
  };

  const t = (key) => {
    const dict = translations[currentLang] || translations.en;
    return dict[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, selectLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
